<?php
/**
 * @file   nginx_accel_redirect.module
 * @author António P. P. Almeida <appa@perusio.net>
 * @date   Wed Feb 23 00:18:59 2011
 * 
 * @brief Module that implements accelerated private file transfers for Nginx.
 * 
 */

// Constants that define the options for the settings form.
define('NGINX_ACCEL_REDIRECT_PHP_TRANSFER', 0);
define('NGINX_ACCEL_REDIRECT_NGINX_TRANSFER', 1);


/**
 * Implements hook_help().
 */
function nginx_accel_redirect_help ($path, $arg) {
  switch ($path) {
    case 'admin/help#nginx_accel_redirect':
      $output = t('<p>The Nginx Accel Redirect Module implements the ' .
                  l('XSendfile', 'http://wiki.nginx.org/XSendfile', array('attributes' => array('rel' => 'external'))) . ' facility in Nginx with Drupal.') . '</p>';
      $output .= '<p>' . t('You have to specify a private path at the ' . l(t('file settings page'), 'admin/settings/file-system') . ' and then enable the X-Accel-Redirect transfer at the module ' . l(t('settings page'), 'admin/settings/file-system/nginx-accel-redirect')) . '.</p>';
      return $output;
      break;
    case 'admin/settings/file-system':
      $output = '';
      if (module_exists('help')) {
        $output = '<p>' . t('If using a private file system please enable fast file transfers using X-Accel-Redirect at the module ') . l(t('settings page'), 'admin/settings/file-system/nginx-accel-redirect') . '.</p>';
      }
      return $output;  
      break;
  case 'admin/settings/file-system/nginx-accel-redirect':
     $output = '';
      if (module_exists('help')) {
        $output = '<p>' . t('To use Nginx X-Accel-Redirect for fast private file transfer enable it below.') . '</p>';
        $output .= '<p>' . t('More help at ') . l(t('this page'), 'admin/help#nginx_accel_redirect') . '.</p>';
      }
      return $output;  
      break;
  } 
} // nginx_accel_redirect_help


/**
 * Implements hook_menu_alter().
 * Overriding the default system/files menu handler.
 */
function nginx_accel_redirect_menu_alter(&$items) {
  $items['system/files']['page callback'] = 'nginx_accel_redirect_file_transfer';
} // nginx_accel_redirect_menu_alter


/**
 * Implements hook_menu().
 */
function nginx_accel_redirect_menu() {
  $items = array();

  $items['admin/settings/file-system/nginx-accel-redirect'] = array(
    'title' => 'X-Accel-Redirect File Settings',
    'description' => 'Control how files are transferred when using private files.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nginx_accel_redirect_admin_settings'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
} // nginx_accel_redirect_menu


/**
 * Transfering a private file using the X-Accel-Redirect facility.
 * Mosty stolen from file_download().
 * @see file_download()
 */
function nginx_accel_redirect_file_transfer() {

  $args = func_get_args();
  
  if (!variable_get('nginx_accel_redirect_transfer',
                    NGINX_ACCEL_REDIRECT_PHP_TRANSFER)) {
    call_user_func_array('file_download', $args);
    exit();
  }

  // Merge the remaining arguments from GET['q'], into relative file path.
  $filepath = implode('/', $args);

  if (file_exists(file_create_path($filepath))) {
    $headers = module_invoke_all('file_download', $filepath);
    if (in_array(-1, $headers)) {
      return drupal_access_denied();
    }
    if (count($headers)) {
      foreach ($headers as $header) {
        // To prevent HTTP header injection, we delete new lines that are
        // not followed by a space or a tab.
        // See http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
        $header = preg_replace('/\r?\n(?!\t| )/', '', $header);
        drupal_set_header($header);
      }
      // Setting the X-Accel-Redirect header for Nginx.
      header('X-Accel-Redirect: ' . base_path() . file_create_path($filepath));        
      exit();
    }
  }
  return drupal_not_found();
} // nginx_accel_redirect_file_transfer


/**
 * The module settings form.
 */
function nginx_accel_redirect_admin_settings() {
  $form = array();

  // Add the CSS for styling the Nginx configuration suggestion.
  drupal_add_css(drupal_get_path('module', 'nginx_accel_redirect') . '/nginx_accel_redirect_form.css');
  
  $form['fast_file_transfer'] = array(
    '#type' => 'fieldset',
    '#title' => t('Fast private file transfer for Nginx'),
    '#collapsible' => TRUE,
  );
  $form['fast_file_transfer']['nginx_accel_redirect_transfer'] = array(
    '#type' => 'radios',
    '#title' => t('X-Accel-Redirect: fast private file transfer support for Nginx'),
    '#default_value' => variable_get('nginx_accel_redirect_transfer',
                                     NGINX_ACCEL_REDIRECT_PHP_TRANSFER),
    '#options' => array(NGINX_ACCEL_REDIRECT_PHP_TRANSFER =>
                        t('Files transfered by PHP'),
                        NGINX_ACCEL_REDIRECT_NGINX_TRANSFER =>
                        t('Files transferred by Nginx using X-Accel-Redirect')),
    '#description' => 'Enable X-Accel-Redirect support.'
  );

  $form['fast_file_transfer']['nginx_accel_redirect_config_suggestion'] = array(
    '#type' => 'textarea',
    '#title' => t('X-Accel-Redirect: configuration for protecting the private files directory'),
    '#description' => t('Copy & paste to your vhost Nginx configuration to protect the private files
directory'),
    '#default_value' => nginx_accel_redirect_get_nginx_config(),
    '#rows' => 5,
    '#cols' => 70,
  );

  return system_settings_form($form);
} // nginx_accel_redirect_admin_settings


/** 
 * Generates the suggested Nginx configuration for protecting the private
 *  files directory.
 * 
 * @return string
 *   The suggested configuration for Nginx.
 */
function nginx_accel_redirect_get_nginx_config() {
  $output = '## To be placed at the the top of your vhost configuration (server block).';
  $output .= "\n## Protect the private files directory.\n";
  $output .= 'location ~* /' . file_directory_path() . "/ {\n";
  $output .= "  internal;\n}\n";

  return $output;
} // nginx_accel_redirect_get_nginx_config